### ISSUE TITLE
Storybook does not work as shown in the workshop video

### ISSUE THREAD

**Issue by sudarshang** [kentcdodds/react-workshop#12]
- node version:  v8.4.0
- yarn version: 0.28.4.
- npm version: 5.3.0
- git version: 2.14.1
master sha of my checkout 76f3c5c162df46f545858beca62b4526c18e3185

**Command Run:**

The `npm run setup` does not install storybook. I ended up installing storybook with the following commands

```
npm i -g @storybook/cli
getstorybook
```
Running 

```
npm run build-storybook
npm run storybook
```
Results in the default storybook, not a storybook with the exercises from the workshop. Running grep for `stories` does not provide any matches.

**Other helpful Comments:**
I am teaching myself react using your react workshop video on youtube here
https://www.youtube.com/watch?v=VZaQfb2y6BI
I was trying to replicate what you showed in that video with storybook when I ran into these issues. It is entirely possible I am doing something wrong here.

**Comment by sudarshang** [comment]
Checking git history show you removed them in 6f4d12677b25b4fdc10bbd0de806b2e577627ba2. Feel free to ignore this as I was able to get the storybook going by checkout aca94d7

**Comment by kentcdodds** [comment]
Hi @sudarshang!
I'm glad that you're working through the workshop! As you can tell, I'm updating it to the latest version of tools and making a few changes to how folks follow along. Would you mind [making a pull request](http://makeapullrequest.com/) to add a note to the README with something like:

```
This repository has been used to teach React several times and has been updated a few times as well.
If you're following along from [this recording](https://www.youtube.com/watch?v=VZaQfb2y6BI),
then you can get to the right spot by running `git checkout aca94d7` before running the setup script. 
```

**Comment by sudarshang** [comment]
Fixed by [PR 13](https://github.com/kentcdodds/react-workshop/pull/13)
